from typing import Dict, List, Tuple


LANDLINE_PREFIX_PROVINCES: Dict[str, Tuple[str, str]] = {
    '011': ('Gauteng', 'HIGH'),
    '012': ('Gauteng', 'HIGH'),
    '013': ('Mpumalanga', 'HIGH'),
    '014': ('North West', 'HIGH'),
    '015': ('Limpopo', 'HIGH'),
    '016': ('North West', 'HIGH'),
    '017': ('Gauteng', 'HIGH'),
    '018': ('Free State', 'HIGH'),
    '021': ('Western Cape', 'HIGH'),
    '022': ('Western Cape', 'HIGH'),
    '023': ('Eastern Cape', 'HIGH'),
    '024': ('Northern Cape', 'HIGH'),
    '027': ('Mpumalanga', 'HIGH'),
    '028': ('Eastern Cape', 'HIGH'),
    '031': ('KwaZulu-Natal', 'HIGH'),
    '032': ('KwaZulu-Natal', 'HIGH'),
    '033': ('KwaZulu-Natal', 'HIGH'),
    '034': ('KwaZulu-Natal', 'HIGH'),
    '035': ('KwaZulu-Natal', 'HIGH'),
    '036': ('KwaZulu-Natal', 'HIGH'),
    '037': ('KwaZulu-Natal', 'HIGH'),
    '038': ('KwaZulu-Natal', 'HIGH'),
    '041': ('Eastern Cape', 'HIGH'),
    '042': ('Eastern Cape', 'HIGH'),
    '043': ('Eastern Cape', 'HIGH'),
    '044': ('Eastern Cape', 'HIGH'),
    '045': ('Eastern Cape', 'HIGH'),
    '046': ('Eastern Cape', 'HIGH'),
    '047': ('Western Cape', 'HIGH'),
    '048': ('Western Cape', 'HIGH'),
    '051': ('Free State', 'HIGH'),
    '052': ('Free State', 'HIGH'),
    '053': ('Free State', 'HIGH'),
    '054': ('Northern Cape', 'HIGH'),
    '055': ('Northern Cape', 'HIGH'),
    '056': ('Free State', 'HIGH'),
    '057': ('Free State', 'HIGH'),
    '058': ('Northern Cape', 'HIGH'),
}


LANDLINE_AREA_CODES: Dict[str, str] = {
    '11': 'Gauteng (Johannesburg)',
    '12': 'Gauteng (Pretoria)',
    '13': 'Mpumalanga (Witbank)',
    '14': 'North West (Rustenburg)',
    '15': 'Limpopo (Polokwane)',
    '16': 'North West (Mafikeng)',
    '17': 'Gauteng (Kempton Park)',
    '18': 'Free State (Bloemfontein)',
    '21': 'Western Cape (Cape Town)',
    '22': 'Western Cape (Mossel Bay)',
    '23': 'Eastern Cape (East London)',
    '24': 'Northern Cape (Kimberley)',
    '27': 'Mpumalanga (Nelspruit)',
    '28': 'Eastern Cape (Mthatha)',
    '31': 'KwaZulu-Natal (Durban)',
    '32': 'KwaZulu-Natal (Pietermaritzburg)',
    '33': 'KwaZulu-Natal (Richards Bay)',
    '34': 'KwaZulu-Natal (Newcastle)',
    '41': 'Eastern Cape (Port Elizabeth)',
    '42': 'Eastern Cape (Uitenhage)',
    '44': 'Eastern Cape (Knysna)',
    '45': 'Eastern Cape (George)',
    '46': 'Eastern Cape (Caledon)',
    '47': 'Western Cape (Hermanus)',
    '48': 'Western Cape (Worcester)',
    '51': 'Free State (Bloemfontein)',
    '52': 'Free State (Welkom)',
    '53': 'Free State (Winburg)',
    '56': 'Free State (Thaba Nchu)',
    '57': 'Free State (Ladybrand)',
    '58': 'Northern Cape (Kimberley)',
}


MOBILE_PREFIX_PROVINCES: Dict[str, List[str]] = {
    '60': ['Gauteng', 'Limpopo', 'North West'],
    '61': ['Gauteng', 'Mpumalanga'],
    '62': ['KwaZulu-Natal', 'Gauteng'],
    '63': ['Gauteng', 'Eastern Cape'],
    '64': ['Western Cape', 'Eastern Cape'],
    '65': ['Eastern Cape', 'Northern Cape'],
    '66': ['Gauteng', 'Free State'],
    '67': ['Limpopo', 'Mpumalanga'],
    '68': ['Mpumalanga', 'Limpopo'],
    '71': ['Western Cape', 'Gauteng'],
    '72': ['Western Cape', 'Eastern Cape'],
    '73': ['Gauteng', 'North West'],
    '74': ['Free State', 'Gauteng'],
    '75': ['Free State', 'Northern Cape'],
    '76': ['KwaZulu-Natal', 'Mpumalanga'],
    '78': ['Gauteng', 'Free State'],
    '79': ['Northern Cape', 'Free State'],
    '81': ['Limpopo', 'North West'],
    '82': ['Mpumalanga', 'Limpopo'],
    '83': ['Free State', 'North West'],
    '84': ['Gauteng', 'KwaZulu-Natal'],
    '85': ['North West', 'Gauteng'],
    '87': ['Eastern Cape', 'Western Cape'],
    '88': ['Northern Cape', 'Free State'],
    '91': ['Gauteng', 'Western Cape'],
    '92': ['Western Cape', 'Gauteng'],
}


MOBILE_PREFIX_TO_PROVINCE: Dict[str, str] = {
    prefix: provinces[0] for prefix, provinces in MOBILE_PREFIX_PROVINCES.items()
}
